[package]
name = "m2g"
version = "0.1.0"
edition = "2021"
description = "Simple cli for translating maven dependencies to gradle"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roxmltree = "0.15.1"
